src/Entity/FactureDon.php
<?php

namespace App\Entity;

use App\Repository\FactureDonRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: FactureDonRepository::class)]
class FactureDon
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le champ Nom du donateur ne peut pas être vide.")]
    #[Assert\Length(max: 255, maxMessage: "Le champ Nom du donateur ne peut pas dépasser 255 caractères.")]
    #[Assert\Regex(
        pattern: '/^\D+$/',
        message: "Le champ Nom du donateur ne peut pas contenir des chiffres."
    )]
    private ?string $nom_donateur = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le champ Prénom du donateur ne peut pas être vide.")]
    #[Assert\Length(max: 255, maxMessage: "Le champ Prénom du donateur ne peut pas dépasser 255 caractères.")]
    #[Assert\Regex(
        pattern: '/^\D+$/',
        message: "Le champ Prénom du donateur ne peut pas contenir des chiffres."
    )]
    private ?string $prenom_donateur = null;
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le champ Email ne peut pas être vide.")]
    #[Assert\Email(message: "L'email '{{ value }}' n'est pas valide.")]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le champ Adresse ne peut pas être vide.")]
    #[Assert\Length(max: 255, maxMessage: "Le champ Adresse ne peut pas dépasser 255 caractères.")]
    private ?string $adresses = null;

    #[ORM\Column(type: 'integer')]
    #[Assert\NotBlank(message: "Le champ Numéro de téléphone ne peut pas être vide.")]
    #[Assert\Type(type: 'integer', message: "Le numéro de téléphone doit être un entier.")]
    private ?int $numero_telephone = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le champ Description ne peut pas être vide.")]
    #[Assert\Length(
        min: 4,
        minMessage: "Le champ Description doit avoir au moins 4 caractères.",
        max: 255,
        maxMessage: "Le champ Description ne peut pas dépasser 255 caractères."
    )]

    
    private ?string $description = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Don $don = null;

  

   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomDonateur(): ?string
    {
        return $this->nom_donateur;
    }

    public function setNomDonateur(string $nom_donateur): static
    {
        $this->nom_donateur = $nom_donateur;

        return $this;
    }

    public function getPrenomDonateur(): ?string
    {
        return $this->prenom_donateur;
    }

    public function setPrenomDonateur(string $prenom_donateur): static
    {
        $this->prenom_donateur = $prenom_donateur;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getAdresses(): ?string
    {
        return $this->adresses;
    }

    public function setAdresses(string $adresses): static
    {
        $this->adresses = $adresses;

        return $this;
    }

    public function getNumeroTelephone(): ?int
    {
        return $this->numero_telephone;
    }

    public function setNumeroTelephone(int $numero_telephone): static
    {
        $this->numero_telephone = $numero_telephone;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    // private ?Don $Don = null;

   /* public function getDon(): ?Don
    {
        return $this->Don;
    }

    public function setDon(?Don $Don): static
    {
        $this->Don = $Don;

        return $this;
    }*/

   public function getDon(): ?Don
   {
       return $this->don;
   }

   public function setDon(?Don $don): static
   {
       $this->don = $don;

       return $this;
   }

    
}

src/Controller/FacturedonbackController.php
<?php

namespace App\Controller;

use App\Entity\FactureDon;
use App\Form\FactureDon1Type;
use App\Repository\FactureDonRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;



#[Route('/facturedonback')]
class FacturedonbackController extends AbstractController
{
    #[Route('/', name: 'app_facturedonback_index', methods: ['GET'])]
    public function index(Request $request, PaginatorInterface $paginator, FactureDonRepository $factureDonRepository): Response
    {
        // Récupérer toutes les factures non paginées
        $allFactureDonsQuery = $factureDonRepository->findAllQuery();

        // Paginer les résultats
        $factureDons = $paginator->paginate(
            $allFactureDonsQuery, // Requête à paginer
            $request->query->getInt('page', 1), // Numéro de page par défaut
            10 // Nombre d'éléments par page
        );

        // Rendre la vue avec les résultats paginés
        return $this->render('facturedonback/index.html.twig', [
            'facture_dons' => $factureDons,
        ]);
    }

    #[Route('/new', name: 'app_facturedonback_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $factureDon = new FactureDon();
        $form = $this->createForm(FactureDon1Type::class, $factureDon);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($factureDon);
            $entityManager->flush();

            return $this->redirectToRoute('app_facturedonback_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('facturedonback/new.html.twig', [
            'facture_don' => $factureDon,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_facturedonback_show', methods: ['GET'])]
    public function show(FactureDon $factureDon): Response
    {
        return $this->render('facturedonback/show.html.twig', [
            'facture_don' => $factureDon,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_facturedonback_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, FactureDon $factureDon, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FactureDon1Type::class, $factureDon);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_facturedonback_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('facturedonback/edit.html.twig', [
            'facture_don' => $factureDon,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_facturedonback_delete', methods: ['POST'])]
    public function delete(Request $request, FactureDon $factureDon, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$factureDon->getId(), $request->request->get('_token'))) {
            $entityManager->remove($factureDon);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_facturedonback_index', [], Response::HTTP_SEE_OTHER);
    }




}

templates/facturedonback/_delete_form.html.twig
<form method="post" action="{{ path('app_facturedonback_delete', {'id': facture_don.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ facture_don.id) }}">
    <button class="btn">Delete</button>
</form>

templates/facturedonback/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/facturedonback/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit FactureDon{% endblock %}

{% block body %}
    <h1>Edit FactureDon</h1>

    {{ include('facturedonback/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_facturedonback_index') }}">back to list</a>

    {{ include('facturedonback/_delete_form.html.twig') }}
{% endblock %}

templates/facturedonback/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}FactureDon index{% endblock %}

{% block body %}
    <h1>FactureDon index</h1>


    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_donateur</th>
                <th>Prenom_donateur</th>
                <th>Email</th>
                <th>Adresses</th>
                <th>Numero_telephone</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for facture_don in facture_dons %}
            <tr>
                <td>{{ facture_don.id }}</td>
                <td>{{ facture_don.nomDonateur }}</td>
                <td>{{ facture_don.prenomDonateur }}</td>
                <td>{{ facture_don.email }}</td>
                <td>{{ facture_don.adresses }}</td>
                <td>{{ facture_don.numeroTelephone }}</td>
                <td>{{ facture_don.description }}</td>
                <td>
                    <a href="{{ path('app_facturedonback_show', {'id': facture_don.id}) }}">show</a>
                    <a href="{{ path('app_facturedonback_edit', {'id': facture_don.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# Affichage de la pagination #}
    <div class="pagination">
        {{ knp_pagination_render(facture_dons) }}
    </div>

    <a href="{{ path('app_facturedonback_new') }}">Create new</a>
{% endblock %}

templates/facturedonback/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New FactureDon{% endblock %}

{% block body %}
    <h1>Create new FactureDon</h1>

    {{ include('facturedonback/_form.html.twig') }}

    <a href="{{ path('app_don_new') }}">back to list</a>
{% endblock %}

templates/facturedonback/pdf_file.html.twig
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>facteur donateur</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
		<style>
			body {
				margin: 0;
				padding: 0;
				font-family: 'Arial', sans-serif;
				text-align: center;
				background-image: url('{{ imagePath }}');
				background-size: cover;
				background-position: center;
				background-repeat: no-repeat;
				color: white; /* Text color */
			}


			header {
				background-color: transparent; /* Make the header transparent */
				color: white;
				text-align: center;
				padding: 20px;
				margin-bottom: 20px;
			}

			.card-container {
				display: flex;
				justify-content: center;
				gap: 20px;
				padding: 20px;
			}

			.card {
				flex-basis: 30%; /* Adjust width for three cards in a row */
				border: 2px solid white; /* Blue border */
				border-radius: 10px;
				box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Box shadow for depth */
				transition: transform 0.3s ease-in-out;
			}

			.card:hover {
				transform: scale(1.05); /* Enlarge on hover */
			}

			.card-body {
				padding: 20px;
			}

			.list-group-item {
				list-style: none;
				margin: 10px 0;
				padding: 8px;
				border-radius: 5px;
				background-color: #dee2e6; /* Light gray background for list items */
			}

			.list-group-item strong {
				margin-right: 10px;
			}
			.footer {
				position: fixed; /* Position the footer at the bottom */
				bottom: 0;
				width: 100%; /* Set width to 100% */
				text-align: center;
				padding: 10px;
				color: white;
			}
		</style>
	</head>
	<body>
		<header>
			<h1 style="color : #007bff">facture donateur</h1>
		</header>

		<div class="card-container">
	{% for factureDon in factureDons %}
		<div class="card text-left">
			<div class="card-header">
				<h5 class="card-title">Facture Donateur ID: {{ factureDon.id }}</h5>
			</div>
			<div class="card-body">
				<p><strong>Nom donateur:</strong> {{ factureDon.nomDonateur }}</p>
				<p><strong>Adresse donateur:</strong> {{ factureDon.adresses }}</p>
				<p><strong>Tel donateur:</strong> {{ factureDon.numeroTelephone }}</p>
			</div>
		</div>
		<br>
	{% endfor %}
	<div class="footer">
		Generated on: {{ "now"|date("Y-m-d H:i:s") }}
	</div>
</div>

	</body>

</html>

templates/facturedonback/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}FactureDon{% endblock %}

{% block body %}
    <h1>FactureDon</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ facture_don.id }}</td>
            </tr>
            <tr>
                <th>Nom_donateur</th>
                <td>{{ facture_don.nomDonateur }}</td>
            </tr>
            <tr>
                <th>Prenom_donateur</th>
                <td>{{ facture_don.prenomDonateur }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ facture_don.email }}</td>
            </tr>
            <tr>
                <th>Adresses</th>
                <td>{{ facture_don.adresses }}</td>
            </tr>
            <tr>
                <th>Numero_telephone</th>
                <td>{{ facture_don.numeroTelephone }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ facture_don.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_facturedonback_index') }}">back to list</a>

    <a href="{{ path('app_facturedonback_edit', {'id': facture_don.id}) }}">edit</a>

    {{ include('facturedonback/_delete_form.html.twig') }}
{% endblock %}